/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Action {
  name: string
  do: () => void
  undo: () => void
}

export interface Dictionary {
  tokens: any
  allTokens: Array<TransformedToken>
}

export interface Format {
  name: string
  format: (arg: FormatArguments) => string
}

export interface FormatArguments {
  dictionary: Dictionary
}

export interface OriginalToken {
  type: string
  value: string
}

export interface Parser {
  name: string
  pattern: string
  parser: (arg: TokenFile) => string
}

export interface Platform {
  name: string
  transformGroup: string
  buildPath: string
  files: Array<PlatformFile>
}

export interface PlatformFile {
  destination: string
  filter?: (arg: any) => boolean
  format: string
}

export interface TokenAttrs {
  category?: string
  type?: string
  item?: string
  subitem?: string
  state?: string
}

export interface TokenFile {
  path: string
  content: string
}

export interface Transform {
  name: string
  kind: TransformKind
  filter: (arg: TransformedToken) => boolean
  transform: (arg: TransformedToken) => string
}

export interface TransformedToken {
  key: string
  value: string
  filePath: string
  isSource: boolean
original: OriginalToken & { [k: string]: any }
name: string
attributes: TokenAttrs
path: Array<string>
}

export interface TransformGroup {
  name: string
  transforms: Array<string>
}

export declare const enum TransformKind {
  Name = 'Name',
  Value = 'Value'
}
export declare class Nephrit {
  constructor(config: NephriteConfig)
  buildPlatform(platformName: string): void
  buildAll(): void
  registerTransform(transform: Transform): void
  registerTransformGroup(transformGroup: TransformGroup): void
  registerParser(parser: Parser): void
  registerAction(action: Action): void
  registerFormat(format: Format): void
}
export type JsNephrit = Nephrit

export interface NephriteConfig {
  source: Array<string>
  cwd?: string
  platforms: Array<Platform>
  logLevel?: NephritLogLevel
}

export declare const enum NephritLogLevel {
  Off = 0,
  Error = 1,
  Warn = 2,
  Info = 3,
  Debug = 4,
  Trace = 5
}
