/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Action {
  name: string
  do: () => void
  undo: () => void
}

export interface Parser {
  name: string
  pattern: string
  parser: (arg: TokenFile) => string
}

export interface Platform {
  name: string
  transformGroup: string
  buildPath: string
}

export interface Token {
  type: string
  value: string
}

export interface TokenFile {
  path: string
  content: string
}

export interface Transform {
  name: string
  kind: TransformKind
  filter: (arg: Token) => boolean
  transform: (arg: Token) => string
}

export interface TransformGroup {
  name: string
  transforms: Array<string>
}

export declare const enum TransformKind {
  Attribute = 'Attribute',
  Value = 'Value'
}
export declare class Nephrite {
  constructor(config: Config)
  getConfig(): Config
  build(platformName: string): void
  registerTransform(transform: Transform): void
  registerTransformGroup(transformGroup: TransformGroup): void
  registerParser(parser: Parser): void
  registerAction(action: Action): void
}

export interface Config {
  source: Array<string>
  cwd?: string
  platforms: Array<Platform>
}
